const lessonTitle = "向生命鞠躬";

const lessonData = [
    // ===== 第 1 段 =====
    ["早就", "zǎo jiù", "long ago", "lama dahulu"],
    ["想", "xiǎng", "want", "hendak"],
    ["带", "dài", "bring", "bawa"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["爬", "pá", "climb", "mendaki"],
    ["一次", "yí cì", "once", "sekali"],
    ["山", "shān", "mountain", "gunung"],
    ["。", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["和", "hé", "and", "dan"],
    ["锻炼", "duàn liàn", "exercise", "senaman"],
    ["身体", "shēn tǐ", "body", "badan"],
    ["无关", "wú guān", "has nothing to do with", "tiada kaitan dengan"],
    ["，", "", "", ""],
    ["而是", "ér shì", "but rather", "sebaliknya"],
    ["想", "xiǎng", "want", "hendak"],
    ["让", "ràng", "let", "biar"],
    ["他", "tā", "him", "dia"],
    ["尽早", "jǐn zǎo", "as early as possible", "seawal mungkin"],
    ["知道", "zhī dào", "know", "tahu"],
    ["世界", "shì jiè", "world", "dunia"],
    ["不仅仅", "bù jǐn jǐn", "not only", "bukan sahaja"],
    ["是", "shì", "is", "ialah"],
    ["由", "yóu", "by", "oleh"],
    ["电视", "diàn shì", "television", "televisyen"],
    ["、", "", "", ""],
    ["高楼", "gāo lóu", "tall buildings", "bangunan tinggi"],
    ["以及", "yǐ jí", "as well as", "serta"],
    ["汽车", "qì chē", "cars", "kereta"],
    ["这些", "zhè xiē", "these", "ini"],
    ["人造的", "rén zào de", "man-made", "buatan manusia"],
    ["东西", "dōng xi", "things", "benda"],
    ["构成", "gòu chéng", "made up of", "terdiri daripada"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["只是", "zhǐ shì", "however", "namun"],
    ["这一", "zhè yī", "this", "ini"],
    ["想法", "xiǎng fǎ", "idea", "idea"],
    ["的", "de", "", ""],
    ["实现", "shí xiàn", "realization", "tercapai"],
    ["已", "yǐ", "already", "sudah"],
    ["是", "shì", "is", "ialah"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["两岁半", "liǎng suì bàn", "two and a half years old", "dua tahun setengah"],
    ["时", "shí", "at that time", "pada masa"],
    ["的", "de", "", ""],
    ["初冬", "chū dōng", "early winter", "awal musim sejuk"],
    ["季节", "jì jié", "season", "musim"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["初冬", "chū dōng", "Early winter", "Awal musim sejuk"],
    ["的", "de", "", ""],
    ["山上", "shān shàng", "on the mountain", "di atas gunung"],
    ["满目", "mǎn mù", "as far as the eye can see", "pemandangan"],
    ["萧瑟", "xiāo sè", "bleak", "sunyi sepi"],
    ["。", "", "", ""],
    ["刈剩", "yì shèng", "leftover after harvesting", "sisa selepas menuai"],
    ["的", "de", "", ""],
    ["麦茬", "mài chá", "wheat stubble", "tunggul gandum"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["黄中带黑", "huáng zhōng dài hēi", "yellowish black", "kuning kehitaman"],
    ["，", "", "", ""],
    ["本就", "běn jiù", "originally", "pada asalnya"],
    ["稀拉", "xī lā", "sparse", "jarang"],
    ["的", "de", "", ""],
    ["树木", "shù mù", "trees", "pokok"],
    ["因", "yīn", "because of", "kerana"],
    ["枯叶", "kū yè", "withered leaves", "daun kering"],
    ["的", "de", "", ""],
    ["飘落", "piāo luò", "falling", "berguguran"],
    ["更显", "gèng xiǎn", "appear even more", "kelihatan lebih"],
    ["孤单", "gū dān", "lonely", "kesepian"],
    ["，", "", "", ""],
    ["黄土地", "huáng tǔ dì", "yellow earth", "tanah kuning"],
    ["少了", "shǎo le", "lacking", "kurang"],
    ["绿色", "lǜ sè", "green", "hijau"],
    ["的", "de", "", ""],
    ["润泽", "rùn zé", "moisture", "kelembapan"],
    ["了无生气", "liǎo wú shēng qì", "lifeless", "tiada kehidupan"],
    ["。", "", "", ""],
    ["因此", "yīn cǐ", "therefore", "Oleh itu"],
    ["，", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["了", "le", "", ""],
    ["一只", "yì zhī", "a", "seekor"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["并", "bìng", "and", "dan"],
    ["指", "zhǐ", "pointed", "menunjuk"],
    ["给", "gěi", "to", "kepada"],
    ["我", "wǒ", "me", "saya"],
    ["看", "kàn", "look", "lihat"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["也", "yě", "also", "juga"],
    ["感到", "gǎn dào", "felt", "berasa"],
    ["十分", "shí fēn", "very", "sangat"],
    ["惊讶", "jīng yà", "surprised", "terkejut"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["想", "xiǎng", "thought", "fikir"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["恐怕", "kǒng pà", "perhaps", "mungkin"],
    ["是", "shì", "is", "ialah"],
    ["山上", "shān shàng", "on the mountain", "di atas gunung"],
    ["唯一", "wéi yī", "only", "satu-satunya"],
    ["还", "hái", "still", "masih"],
    ["倔强", "jué jiàng", "tenaciously", "dengan gigih"],
    ["活着", "huó zhe", "alive", "hidup"],
    ["的", "de", "", ""],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["我", "wǒ", "I", "Saya"],
    ["蹑手蹑脚地", "niè shǒu niè jiǎo de", "stealthily", "dengan perlahan-lahan"],
    ["靠近", "kào jìn", "approached", "mendekati"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["发现", "fā xiàn", "noticed", "perasan"],
    ["有人", "yǒu rén", "someone", "ada orang"],
    ["，", "", "", ""],
    ["蹦了", "bèng le", "jumped", "melompat"],
    ["一下", "yí xià", "once", "sekali"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["显然", "xiǎn rán", "obviously", "jelas"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["很", "hěn", "very", "sangat"],
    ["衰老", "shuāi lǎo", "aged", "tua"],
    ["，", "", "", ""],
    ["才", "cái", "only", "hanya"],
    ["蹦出去", "bèng chū qù", "jumped out", "melompat keluar"],
    ["不到", "bú dào", "less than", "kurang daripada"],
    ["一米", "yī mǐ", "one meter", "satu meter"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["张开", "zhāng kāi", "opened", "buka"],
    ["双手", "shuāng shǒu", "both hands", "kedua-dua tangan"],
    ["，", "", "", ""],
    ["迅疾", "xùn jí", "quickly", "dengan pantas"],
    ["扑过去", "pū guò qù", "pounced over", "menghambur ke arah"],
    ["将", "jiāng", "to", "untuk"],
    ["它", "tā", "it", "ia"],
    ["罩住", "zhào zhù", "covered", "menutupi"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["将", "jiāng", "to", "untuk"],
    ["手指", "shǒu zhǐ", "fingers", "jari"],
    ["裂开", "liè kāi", "opened", "buka"],
    ["一条缝", "yì tiáo fèng", "a crack", "celah"],
    ["，", "", "", ""],
    ["捏着", "niē zhe", "pinched", "mencubit"],
    ["它的", "tā de", "its", "ia punya"],
    ["翅膀", "chì bǎng", "wings", "sayap"],
    ["将", "jiāng", "to", "untuk"],
    ["它", "tā", "it", "ia"],
    ["活捉", "huó zhuō", "caught alive", "tangkap hidup-hidup"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["我", "wǒ", "I", "Saya"],
    ["觉得", "jué de", "thought", "rasa"],
    ["就这样", "jiù zhè yàng", "just like this", "begitu sahaja"],
    ["交给", "jiāo gěi", "hand over to", "serahkan kepada"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["，", "", "", ""],
    ["会", "huì", "will", "akan"],
    ["被", "bèi", "be", "akan"],
    ["它", "tā", "it", "ia"],
    ["挣脱", "zhèng tuō", "break free", "lepaskan diri"],
    ["，", "", "", ""],
    ["于是", "yú shì", "so", "Maka"],
    ["拔了", "bá le", "pulled out", "mencabut"],
    ["一根", "yì gēn", "a", "sebatang"],
    ["干草", "gān cǎo", "dry grass", "rumput kering"],
    ["，", "", "", ""],
    ["将", "jiāng", "to", "untuk"],
    ["细而光", "xì ér guāng", "thin and smooth", "halus dan licin"],
    ["的", "de", "", ""],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["从", "cóng", "from", "dari"],
    ["它", "tā", "its", "ia punya"],
    ["身体", "shēn tǐ", "body", "badan"],
    ["的", "de", "", ""],
    ["末端", "mò duān", "end", "hujung"],
    ["捅进", "tǒng jìn", "pierced into", "menusuk masuk"],
    ["，", "", "", ""],
    ["再", "zài", "then", "kemudian"],
    ["从", "cóng", "from", "dari"],
    ["它的", "tā de", "its", "ia punya"],
    ["嘴里", "zuǐ lǐ", "mouth", "mulut"],
    ["捅出", "tǒng chū", "pierced out", "menusuk keluar"],
    ["——", "", "", ""],
    ["小时候", "xiǎo shí hou", "when I was young", "semasa kecil"],
    ["我们", "wǒ men", "we", "kami"],
    ["抓蚂蚱", "zhuā mà zhà", "catch locusts", "tangkap belalang"],
    ["，", "", "", ""],
    ["为防止", "wèi fáng zhǐ", "to prevent", "untuk mengelakkan"],
    ["其", "qí", "it", "ia"],
    ["逃跑", "táo pǎo", "escape", "melarikan diri"],
    ["都是", "dōu shì", "all", "semuanya"],
    ["这样", "zhè yàng", "like this", "begini"],
    ["做", "zuò", "do", "buat"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["有时", "yǒu shí", "sometimes", "kadang-kadang"],
    ["一根", "yì gēn", "one", "sebatang"],
    ["草杆上", "cǎo gǎn shàng", "on a grass stem", "pada batang rumput"],
    ["要", "yào", "would", "akan"],
    ["穿", "chuān", "thread", "tusuk"],
    ["六七只", "liù qī zhī", "six or seven", "enam tujuh ekor"],
    ["蚂蚱", "mà zhà", "locusts", "belalang"],
    ["。", "", "", ""],
    ["蚂蚱", "mà zhà", "locust", "Belalang"],
    ["的", "de", "", ""],
    ["嘴里", "zuǐ lǐ", "mouth", "mulut"],
    ["滴出", "dī chū", "dripped out", "menitis keluar"],
    ["淡绿", "dàn lǜ", "pale green", "hijau pucat"],
    ["的", "de", "", ""],
    ["液体", "yè tǐ", "liquid", "cecair"],
    ["，", "", "", ""],
    ["那是", "nà shì", "that was", "itu ialah"],
    ["它的", "tā de", "its", "ia punya"],
    ["血", "xuè", "blood", "darah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["我", "wǒ", "I", "Saya"],
    ["将", "jiāng", "to", "untuk"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["交给", "jiāo gěi", "handed over to", "serahkan kepada"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["，", "", "", ""],
    ["告诉", "gào su", "told", "beritahu"],
    ["他", "tā", "him", "dia"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这叫", "zhè jiào", "this is called", "ini dipanggil"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["，", "", "", ""],
    ["专吃", "zhuān chī", "specializes in eating", "khas makan"],
    ["庄稼", "zhuāng jià", "crops", "tanaman"],
    ["，", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["害虫", "hài chóng", "pest", "perosak"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["儿子", "ér zi", "son", "Anak lelaki"],
    ["似懂非懂地", "sì dǒng fēi dǒng de", "half-understanding", "separuh faham"],
    ["点头", "diǎn tóu", "nodded", "mengangguk"],
    ["，", "", "", ""],
    ["握住", "wò zhù", "held", "memegang"],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["，", "", "", ""],
    ["将", "jiāng", "to", "untuk"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["盯了", "dīng le", "stared at", "merenung"],
    ["半天", "bàn tiān", "for a long time", "lama"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["又", "yòu", "again", "lagi"],
    ["继续", "jì xù", "continued", "terus"],
    ["低头", "dī tóu", "lowered his head", "menunduk"],
    ["用", "yòng", "with", "dengan"],
    ["树枝", "shù zhī", "branch", "dahan"],
    ["专心致志地", "zhuān xīn zhì zhì de", "concentratedly", "dengan tekun"],
    ["刨土", "páo tǔ", "digging soil", "menggali tanah"],
    ["。", "", "", ""],
    ["儿子", "ér zi", "son", "Anak lelaki"],
    ["还没有", "hái méi yǒu", "not yet", "belum"],
    ["益虫", "yì chóng", "beneficial insects", "serangga berfaedah"],
    ["、", "", "", ""],
    ["害虫", "hài chóng", "pests", "perosak"],
    ["的", "de", "", ""],
    ["概念", "gài niàn", "concept", "konsep"],
    ["，", "", "", ""],
    ["在", "zài", "in", "di"],
    ["他", "tā", "his", "dia punya"],
    ["眼里", "yǎn lǐ", "eyes", "mata"],
    ["一切", "yí qiè", "everything", "semuanya"],
    ["都", "dōu", "all", "semua"],
    ["很", "hěn", "very", "sangat"],
    ["新鲜", "xīn xiān", "fresh", "baru"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["“", "", "", ""],
    ["跑了", "pǎo le", "ran away", "lari"],
    ["！", "", "", ""],
    ["跑了", "pǎo le", "ran away", "lari"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["儿子", "ér zi", "son", "Anak lelaki"],
    ["忽然", "hū rán", "suddenly", "tiba-tiba"],
    ["急切地", "jí qiè de", "urgently", "dengan terburu-buru"],
    ["叫起来", "jiào qǐ lái", "shouted out", "menjerit"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["扭头", "niǔ tóu", "turned my head", "memusingkan kepala"],
    ["看见", "kàn jiàn", "saw", "melihat"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["只", "zhǐ", "only", "hanya"],
    ["握着", "wò zhe", "holding", "memegang"],
    ["一根", "yì gēn", "a", "sebatang"],
    ["光秃秃的", "guāng tū tū de", "bare", "botak"],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["，", "", "", ""],
    ["上面", "shàng miàn", "on it", "di atasnya"],
    ["的", "de", "", ""],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["已", "yǐ", "already", "sudah"],
    ["不翼而飞", "bù yì ér fēi", "vanished", "hilang lenyap"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["连忙", "lián máng", "hurriedly", "segera"],
    ["跟", "gēn", "followed", "ikut"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["四处", "sì chù", "everywhere", "merata-rata"],
    ["找", "zhǎo", "look for", "cari"],
    ["。", "", "", ""],
    ["其实", "qí shí", "in fact", "sebenarnya"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["并未", "bìng wèi", "did not", "tidak"],
    ["逃出", "táo chū", "escape far", "lari jauh"],
    ["多远", "duō yuǎn", "far", "jauh"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["只是", "zhǐ shì", "just", "hanya"],
    ["在地上", "zài dì shàng", "on the ground", "di atas tanah"],
    ["艰难地", "jiān nán de", "painfully", "dengan susah payah"],
    ["爬", "pá", "crawl", "merangkak"],
    ["，", "", "", ""],
    ["间或", "jiàn huò", "occasionally", "kadang-kadang"],
    ["无力地", "wú lì de", "weakly", "dengan lemah"],
    ["跳一下", "tiào yí xià", "jump once", "melompat sekali"],
    ["，", "", "", ""],
    ["因此", "yīn cǐ", "therefore", "oleh itu"],
    ["我", "wǒ", "I", "saya"],
    ["轻易地", "qīng yì de", "easily", "dengan mudah"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["了", "le", "", ""],
    ["它", "tā", "it", "ia"],
    ["，", "", "", ""],
    ["再一次", "zài yī cì", "once again", "sekali lagi"],
    ["将", "jiāng", "to", "untuk"],
    ["它", "tā", "it", "ia"],
    ["生擒", "shēng qín", "captured alive", "tangkap hidup-hidup"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["将", "jiāng", "to", "untuk"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["重先", "chóng xiān", "again", "semula"],
    ["穿回", "chuān huí", "threaded back", "tusuk kembali"],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["，", "", "", ""],
    ["所不同的是", "suǒ bù tóng de shì", "the difference was", "perbezaannya ialah"],
    ["，", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["又", "yòu", "again", "lagi"],
    ["开始", "kāi shǐ", "started", "mula"],
    ["兴致勃勃地", "xìng zhì bó bó de", "enthusiastically", "dengan bersemangat"],
    ["刨土", "páo tǔ", "digging soil", "menggali tanah"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["离开", "lí kāi", "leave", "pergi"],
    ["，", "", "", ""],
    ["想", "xiǎng", "want", "hendak"],
    ["看看", "kàn kan", "see", "lihat"],
    ["这小玩意", "zhè xiǎo wán yì", "this little thing", "benda kecil ini"],
    ["究竟", "jiū jìng", "after all", "sebenarnya"],
    ["用", "yòng", "use", "guna"],
    ["何种", "hé zhǒng", "what kind of", "apa jenis"],
    ["方法", "fāng fǎ", "method", "cara"],
    ["逃跑", "táo pǎo", "escape", "melarikan diri"],
    ["的", "de", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["儿子", "ér zi", "son", "Anak lelaki"],
    ["手里", "shǒu lǐ", "in hand", "di tangan"],
    ["握着的", "wò zhe de", "holding", "memegang"],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["不经意间", "bù jīng yì jiān", "accidentally", "secara tidak sengaja"],
    ["碰到了", "pèng dào le", "touched", "tersentuh"],
    ["旁边", "páng biān", "beside", "di sisi"],
    ["的", "de", "", ""],
    ["一丛", "yì cóng", "a cluster of", "sepokok"],
    ["枯草", "kū cǎo", "withered grass", "rumput kering"],
    ["，", "", "", ""],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["迅速", "xùn sù", "quickly", "dengan cepat"],
    ["将", "jiāng", "to", "untuk"],
    ["一根", "yì gēn", "a", "sebatang"],
    ["草茎", "cǎo jīng", "grass stem", "batang rumput"],
    ["抱住", "bào zhù", "grasped", "memeluk"],
    ["。", "", "", ""],
    ["随着", "suí zhe", "as", "sambil"],
    ["儿子的手", "ér zi de shǒu", "son's hand", "tangan anak lelaki"],
    ["抬高", "tái gāo", "raised", "angkat tinggi"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["穿着", "chuān zhe", "threaded with", "yang ditusuk"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["的", "de", "", ""],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["渐成", "jiàn chéng", "gradually became", "semakin menjadi"],
    ["弓形", "gōng xíng", "bow-shaped", "bentuk busur"],
    ["，", "", "", ""],
    ["可是", "kě shì", "however", "namun"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["死死地", "sǐ sǐ de", "firmly", "dengan erat"],
    ["抱住", "bào zhù", "held onto", "memeluk"],
    ["草茎", "cǎo jīng", "grass stem", "batang rumput"],
    ["。", "", "", ""],
    ["难以想象", "nán yǐ xiǎng xiàng", "hard to imagine", "sukar dibayangkan"],
    ["这", "zhè", "this", "ini"],
    ["如此", "rú cǐ", "so", "begitu"],
    ["孱弱", "chán ruò", "weak", "lemah"],
    ["受着", "shòu zhe", "suffering", "mengalami"],
    ["重创", "zhòng chuāng", "severe injury", "cedera parah"],
    ["的", "de", "", ""],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["竟", "jìng", "actually", "sebenarnya"],
    ["还有", "hái yǒu", "still have", "masih ada"],
    ["这么", "zhè me", "so", "begitu"],
    ["大的", "dà de", "great", "besar"],
    ["力量", "lì liàng", "strength", "kekuatan"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["儿子", "ér zi", "son", "Anak lelaki"],
    ["手", "shǒu", "hand", "tangan"],
    ["一松", "yì sōng", "loosened", "longgarkan"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["就开始", "jiù kāi shǐ", "then began", "mula"],
    ["艰难地", "jiān nán de", "painfully", "dengan susah payah"],
    ["顺着", "shùn zhe", "along", "menyusur"],
    ["草茎", "cǎo jīng", "grass stem", "batang rumput"],
    ["往上爬", "wǎng shàng pá", "climb up", "memanjat ke atas"],
    ["。", "", "", ""],
    ["穿出", "chuān chū", "piercing out", "menusuk keluar"],
    ["它", "tā", "its", "ia punya"],
    ["嘴", "zuǐ", "mouth", "mulut"],
    ["的", "de", "", ""],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["在", "zài", "was", "sedang"],
    ["一点一点", "yì diǎn yì diǎn", "little by little", "sedikit demi sedikit"],
    ["缩短", "suō duǎn", "shortening", "semakin pendek"],
    ["，", "", "", ""],
    ["退出", "tuì chū", "withdrawing from", "keluar dari"],
    ["它", "tā", "its", "ia punya"],
    ["身体的", "shēn tǐ de", "body", "badan"],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["已被", "yǐ bèi", "had been", "telah"],
    ["它的血", "tā de xuè", "its blood", "darahnya"],
    ["染得", "rǎn de", "stained", "menjadi"],
    ["微绿", "wēi lǜ", "slightly green", "kehijauan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["我", "wǒ", "I", "Saya"],
    ["张大", "zhāng dà", "opened wide", "buka luas"],
    ["嘴巴", "zuǐ ba", "mouth", "mulut"],
    ["，", "", "", ""],
    ["看得", "kàn de", "watched", "melihat"],
    ["出了神", "chū le shén", "transfixed", "terpaku"],
    ["。", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["心", "xīn", "heart", "hati"],
    ["被", "bèi", "was", "telah"],
    ["悲壮的", "bēi zhuàng de", "tragic and heroic", "sedih dan gagah"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["强烈", "qiáng liè", "intensely", "sangat"],
    ["震撼", "zhèn hàn", "shaken", "terkejut"],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["所", "suǒ", "what", "apa yang"],
    ["忍受的", "rěn shòu de", "endured", "tanggung"],
    ["疼痛", "téng tòng", "pain", "sakit"],
    ["我们", "wǒ men", "we", "kita"],
    ["人类", "rén lèi", "human beings", "manusia"],
    ["不可能", "bù kě néng", "impossible", "tidak mungkin"],
    ["忍受", "rěn shòu", "endure", "tahan"],
    ["。", "", "", ""],
    ["它的", "tā de", "its", "ia punya"],
    ["壮举", "zhuàng jǔ", "feat", "perbuatan agung"],
    ["在", "zài", "in", "di"],
    ["人世间", "rén shì jiān", "the human world", "dunia ini"],
    ["也", "yě", "also", "juga"],
    ["不可能", "bù kě néng", "impossible", "tidak mungkin"],
    ["发生", "fā shēng", "happen", "berlaku"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["相信", "xiāng xìn", "believe", "percaya"],
    ["，", "", "", ""],
    ["自己", "zì jǐ", "myself", "saya sendiri"],
    ["正在", "zhèng zài", "am", "sedang"],
    ["目睹", "mù dǔ", "witnessing", "menyaksikan"],
    ["一个", "yí gè", "a", "satu"],
    ["奇迹", "qí jì", "miracle", "keajaiban"],
    ["，", "", "", ""],
    ["我想", "wǒ xiǎng", "I think", "saya rasa"],
    ["这是", "zhè shì", "this is", "ini ialah"],
    ["并非", "bìng fēi", "not", "bukan"],
    ["所有人", "suǒ yǒu rén", "everyone", "semua orang"],
    ["都", "dōu", "all", "semua"],
    ["有幸", "yǒu xìng", "have the fortune", "berpeluang"],
    ["目睹的", "mù dǔ de", "to witness", "untuk menyaksikan"],
    ["生命的", "shēng mìng de", "life's", "kehidupan"],
    ["奇迹", "qí jì", "miracle", "keajaiban"],
    ["。", "", "", ""],
    ["等", "děng", "when", "apabila"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["将", "jiāng", "to", "untuk"],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["从", "cóng", "from", "dari"],
    ["身体", "shēn tǐ", "body", "badan"],
    ["里", "lǐ", "from", "dari"],
    ["完全", "wán quán", "completely", "sepenuhnya"],
    ["退出后", "tuì chū hòu", "withdrew", "setelah keluar"],
    ["，", "", "", ""],
    ["反而", "fǎn ér", "instead", "sebaliknya"],
    ["腿", "tuǐ", "legs", "kaki"],
    ["一松", "yì sōng", "loosened", "longgarkan"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "dari"],
    ["所抱的", "suǒ bào de", "the one it grasped", "yang dipeluknya"],
    ["草茎上", "cǎo jīng shàng", "grass stem", "batang rumput"],
    ["滚落", "gǔn luò", "rolled off", "jatuh berguling"],
    ["到", "dào", "to", "ke"],
    ["地上", "dì shàng", "the ground", "tanah"],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["一定", "yí dìng", "must be", "pasti"],
    ["是", "shì", "is", "ialah"],
    ["筋疲力尽", "jīn pí lì jìn", "exhausted", "keletihan"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["儿子", "ér zi", "son", "Anak lelaki"],
    ["手", "shǒu", "hand", "tangan"],
    ["握着", "wò zhe", "holding", "memegang"],
    ["草杆", "cǎo gǎn", "grass stem", "batang rumput"],
    ["再也没有", "zài yě méi yǒu", "no longer", "tidak lagi"],
    ["动", "dòng", "move", "bergerak"],
    ["。", "", "", ""],
    ["原来", "yuán lái", "it turned out", "rupanya"],
    ["他", "tā", "he", "dia"],
    ["和", "hé", "and", "dan"],
    ["我", "wǒ", "me", "saya"],
    ["一样", "yí yàng", "the same", "sama"],
    ["，", "", "", ""],
    ["在", "zài", "were", "sedang"],
    ["呆呆地", "dāi dāi de", "dazedly", "termenung"],
    ["盯着", "dīng zhe", "staring at", "merenung"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["的", "de", "", ""],
    ["一举一动", "yī jǔ yī dòng", "every move", "setiap gerakan"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["为之", "wèi zhī", "at it", "kagum"],
    ["震惊", "zhèn jīng", "shocked", "terkejut"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["慢慢", "màn màn", "slowly", "perlahan-lahan"],
    ["站起来", "zhàn qǐ lái", "stood up", "berdiri"],
    ["，", "", "", ""],
    ["随即", "suí jí", "then", "kemudian"],
    ["向前", "xiàng qián", "forward", "ke hadapan"],
    ["微微", "wēi wēi", "slightly", "sedikit"],
    ["弯腰", "wān yāo", "bent over", "membongkok"],
    ["。", "", "", ""],
    ["儿子", "ér zi", "son", "Anak lelaki"],
    ["以为", "yǐ wéi", "thought", "fikir"],
    ["我", "wǒ", "I", "saya"],
    ["又要", "yòu yào", "again going to", "hendak lagi"],
    ["抓", "zhuā", "catch", "tangkap"],
    ["蚂蚱", "mà zhà", "locust", "belalang"],
    ["，", "", "", ""],
    ["连忙", "lián máng", "hurriedly", "segera"],
    ["喊", "hǎn", "shouted", "jerit"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["别", "bié", "don't", "jangan"],
    ["，", "", "", ""],
    ["别", "bié", "don't", "jangan"],
    ["，", "", "", ""],
    ["别动", "bié dòng", "don't move", "jangan sentuh"],
    ["它", "tā", "it", "ia"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["明白", "míng bái", "understood", "faham"],
    ["儿子的意思", "ér zi de yì si", "what my son meant", "maksud anak lelaki"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "but", "Tetapi"],
    ["，", "", "", ""],
    ["儿子", "ér zi", "son", "Anak lelaki"],
    ["大概", "dà gài", "perhaps", "mungkin"],
    ["永远", "yǒng yuǎn", "never", "tidak akan"],
    ["也", "yě", "also", "juga"],
    ["不会", "bù huì", "will not", "tidak akan"],
    ["明白", "míng bái", "understand", "faham"],
    ["我", "wǒ", "I", "saya"],
    ["弯腰", "wān yāo", "bending", "membongkok"],
    ["的", "de", "", ""],
    ["意思", "yì si", "meaning", "maksud"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["几乎", "jī hū", "almost", "hampir"],
    ["是", "shì", "was", "ialah"],
    ["在", "zài", "in", "dalam"],
    ["下意识地", "xià yì shí de", "subconsciously", "secara tidak sedar"],
    ["鞠躬", "jū gōng", "bowed", "menunduk"],
    ["，", "", "", ""],
    ["向", "xiàng", "to", "kepada"],
    ["一个", "yí gè", "a", "satu"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["、", "", "", ""],
    ["一个", "yí gè", "a", "satu"],
    ["顽强的", "wán qiáng de", "tenacious", "tabah"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["鞠躬", "jū gōng", "bowed", "menunduk"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["李志林", "lǐ zhì lín", "Li Zhilin", "Li Zhilin"],
    ["《", "", "", ""],
    ["向生命鞠躬", "xiàng shēng mìng jū gōng", "Bow to Life", "Tunduk kepada Kehidupan"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
